### ISSUE TITLE
Where can I get a DB dump of all restrooms?

### ISSUE THREAD

**Issue by kiesia** [RefugeRestrooms/refugerestrooms#196]

**Comment by gnarf** [comment]
You can scrape the API in like 20 calls - its max per page is like 100

**Comment by gnarf** [comment]
Max was 1000 - missed a zero

http://www.refugerestrooms.org/api/v1/restrooms.json?per_page=10000&page=1

And increase page until you run out

**Comment by kiesia** [comment]
I don't want to hack together code to fetch the restrooms, I want a DB dump. That would be a lot more simple!

**Comment by gnarf** [comment]
For local dev?  Someone could write a rake task to import them from the
live site maybe?

Otherwise a quick dirty json dump can restore the whole thing. I agree
having a db dump would be nice, but it would go out of date unless you
automated it. I find that most sites that have an api rarely offer raw SQL
dumps, and wouldn't want to release them myself if I ran the site.

**Comment by backspace** [comment]
Do you want the current data? If not, you can load the original data by running `rake db:seed`.

**Comment by kiesia** [comment]
I'm interested in the raw data because I want to know where we have restrooms. I live in Berlin and internationalisation is very important for me.

**Comment by kiesia** [comment]
Perhaps someone can just give me deploy rights and I can take a dump from there?

**Comment by tkwidmer** [comment]
@kiesia now has deploy capability and access to refuge on heroku.

**Comment by gnarf** [comment]
That works too, but still doesn't help a new contrib who needs local db --
might still be worth adding a rake task

**Comment by tkwidmer** [comment]
Could be. But lets handle that as a separate issue. For now most folks wont need that to dev with.

If we want to release a SQL database dump, lets make that a separate ticket.
