### ISSUE TITLE
Move from Google Analytics to Piwik

### ISSUE THREAD

**Issue by kiesia** [RefugeRestrooms/refugerestrooms#200]
I've emailed [Enspiral](http://enspiral.com) asking if they are interested in donating a piwik account. If that is not possible, then I'll set up a piwik server on a VM (I can donate hosting for this).

This ticket is coming from discussion in #80.

**Comment by kiesia** [comment]
We have a Piwk account donated by [Enspiral](http://enspiral.com). I'll sublit a PR integrating this within the next couple days.

**Comment by tkwidmer** [comment]
awesome @kiesia

**Comment by kiesia** [comment]
PR #206

**Comment by tkwidmer** [comment]
@kiesia can you add me as an admin in some way on Pikwik so I can see the data and stuff.

**Comment by kiesia** [comment]
@tkwidmer sorry for the delay on this, I'm waiting on admin rights, then I can make you a user.

**Comment by juliofarah** [comment]
Hi there!

I hope I'm not crossing any lines here, I just got here and would like to contribute with the project (running `vagrant up` right now :smile:), but I'd like to as why you'd rather use Piwik instead of Google Analytics.

One issue I've faced with GA is that it's quite hard/impossible to analyze data from China due to the _great firewall_ (fortunately we have a VPN to redirect users to Hong Kong) and Piwik is allowed in China; so I wonder, what are the motivations behind it? 
If refugerestrooms.org is not listed on China's government domains list users would have to use a VNP either way.

I'm actually quite curious because my team decided to abandon Piwki since it would add a bit of extra effort to learn how to use the tool, so we might end up changing our minds with this discussion 😃 

Thanks in advance

**Comment by mi-wood** [comment]
@juliofarah Welcome and thanks! @tkwidmer might no a little more about this, but I'm pretty sure we're trying to move off of google services and that's why we use Piwik instead.

More info here: https://github.com/RefugeRestrooms/refugerestrooms/issues/80
