### ISSUE TITLE
When filtering (ada/inclusive buttons), these filtered results need to apply to all paged results 

### ISSUE THREAD

**Issue by kevjames3** [RefugeRestrooms/refugerestrooms#226]
Example:
- http://www.refugerestrooms.org/restrooms?lat=37.7895781&long=-122.3888351&page=3&search=Current+Location&utf8=%E2%9C%93
- Click both filters
- Click to the next page
- Filters are no longer applied

**Comment by mi-wood** [comment]
going to take a try at this right now and see where I get. might pick it up again tomorrow if no one else is working on it already.

**Comment by azelma** [comment]
@mi-wood are you still on this? I'm happy to take a look.

**Comment by mi-wood** [comment]
@azelma it's in this PR: https://github.com/RefugeRestrooms/refugerestrooms/pull/230

I forget exactly where I left off. I had fixed the bug but went on to start refactoring stuff...

**Comment by DeeDeeG** [comment]
FWIW, a lot of sites use cookies to store user preferences. I have no idea how to set a cookie but I thought I'd mention it.

**Comment by DeeDeeG** [comment]
I wonder: is there a way to just "click" the filter buttons during page load? I am thinking from javascript.

If so, we could persist data the way you've done so far with URLs, and no need for messing with cookies.

(This may reveal that I don't fully understand your PR, but I think these are the right questions to start from/to get the ball rolling [again]).

**Comment by DeeDeeG** [comment]
I ran this branch https://github.com/RefugeRestrooms/refugerestrooms/tree/mi-wood/bug/226-persistent-filter in vagrant a bit, and I saw the issue you mentioned with maps appearing gray. I don't know why, but resizing the page after initially loading the map in makes the map show as expected.

**Comment by mi-wood** [comment]
Maybe we can re-open and tidy it up then 😅

**Comment by DeeDeeG** [comment]
I am at a loss for what makes this happen, so I'm not sure I would be of much help. Javascript isn't one of my strong areas.

If I understood how we are applying the search filters on `develop` branch, I'd be more comfortable with trying to make it work here. So I'll take a look at that as a start.

**Comment by DeeDeeG** [comment]
I have to say, the current setup looks complicated to me. Take this with a pound of salt, since I don't know javascript very well. I wonder if an alternate approach would be easier.

My instinct for this feature would be to try to do it like this:

- Filters off by default or if no filter "state" detected.
- [users click the filter buttons as usual, current page updates instantly] (same as current behavior)
- write the "state" of the filters right away when filter buttons are clicked
    - State stored in the URL, or in a cookie, or somewhere...
      - [if writing the state via URL, update the content of "next page" link at bottom of page to reflect filter states. Read the filter states from the URL on next page load]
      - [if writing the state via cookies, update the filter state in a cookie when filter button pressed. Read the filter states from cookie(s) on next page load]
       - [other options for writing the state?]
- simulate clicking the filter buttons on every pageload, according to any saved "state" of the filters. Filters off by default.

Does this sound like a good plan? Suggestions/comments?

**Comment by DeeDeeG** [comment]
Or to sidestep the issue of how to do filters, since you got that working already (somehow I keep forgetting that that is already solved): Are there any changes to how the map is being shown that can be undone? That part with the gray map really mystifies me the most.

**Comment by mi-wood** [comment]
So, I know about 0 JS and that's part of why this PR is a mess btw :)

Since the actual results are not a very large payload, I think a big upgrade would be to do pagination client side. That's obviously a lot more work and I wouldn't personally know where to start.

The goal of this PR was to simulate what client side filtering might look like. Filters get selected and are sticky within a search (it'd probably be better to session this with a cookie). I left it in kind of a messy state just because I was trying to refactor it and got halfway. I think the approach should still work for a relatively quick fix though.

`simulate clicking the filter buttons on every pageload, according to any saved "state" of the filters. Filters off by default`
So the one issue with this is that you could potentially filter out all your results. It'd be nice to paginate on the filters (ie. show 10 results regardless of which filters are provided)

The gray map thing is what caused me to not finish this out. I spent quite a bit of time trying to figure out what was up, but there isn't even an error anywhere haha.

**Comment by GPrimola** [comment]
Hey @DeeDeeG can I get this one? Or is there someone already on it?

**Comment by DeeDeeG** [comment]
Hi @GPrimola this issue is totally open. Thanks for taking a look!

**Comment by GPrimola** [comment]
Hey @DeeDeeG 

I've started working on this and I'd like to know if keeping the SPA-like behavior of the filters is a requirement?
The 'new' approach would refresh the page on each filter button click. Do you think this option is on the table?

**Comment by DeeDeeG** [comment]
@GPrimola that sounds fine.

It's a pretty light app (less than 1MB over the network on refresh, after visiting and caching the site once). It would be super if the filter(s) would persist as a URL parameter or something like that. But that's not required; Whatever you have I'll be glad to take a look at it.

Thanks again!
