### ISSUE TITLE
Play store icon missing from front page

### ISSUE THREAD

**Issue by jmisacube** [RefugeRestrooms/refugerestrooms#276]
On the front page of http://www.refugerestrooms.org/, the play store icon seems to be missing. Going by https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/app/views/pages/index.html.haml, it _should_ be present, but isn't in the front page's HTML.

**Comment by clado** [comment]
I've noticed this as well, and I think it's because the application hasn't been deployed in a while. If you look at the list of closed pull requests, all of the recent updates can be seen on the master/development branch but not in production.
I'm assuming this is either because the person who usually pushes updates to production is busy right now, or because we want to bundle lots of changes before making a single official release all at once.

**Comment by tkwidmer** [comment]
@clado @jmisacube We haven't been able to deploy for a while because of some changes to heroku's infastructure. I'm going to take care of this at the upcoming hacknight on the 13th.
