### ISSUE TITLE
Yelp just killed Refuge? Whats the way forward? What now?

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#293]
So this happened today: 

https://www.yelpblog.com/2017/03/now-use-yelp-find-gender-neutral-restrooms?sf59947170=1

Yelp is releasing a gender neutral bathroom flag. It's soon going to be able to be searched as a filter for gender neutral bathrooms.

**Comment by clado** [comment]
Hmmmm. Interesting. I'm not sure what our web traffic looks like, but I think RefugeRestrooms would still be very useful for many communities. Most of the bathrooms in my area are in schools, churches, or libraries, which Yelp won't be likely to have data on. I still think there's a purpose for RefugeRestrooms, but I guess we'd have to wait and see. However, it would be super neat to try to use Yelp's API and display some of their data on our maps, as long as that's in compliance with their term of service.

**Comment by Graystripe17** [comment]
If yelp makes it non-corporate, then it accomplishes the same goal as Refuge Restrooms, which was nonprofit anyway. Maybe contact Yelp and exchange data.

**Comment by glassresistor** [comment]
I think a two way sharing of data would be great.  Yelp only listing businesses mean RR would still have an edge, also yelps general purpose means RR can be faster and easier to use especially for those updating the information.

**Comment by tkwidmer** [comment]
It feels weird to just give our data to a for profit company that is going to find a way to make money off of that data.

**Comment by tkwidmer** [comment]
Yelp certianly doesn't display high fidelity information about different building on campus at a school

**Comment by glassresistor** [comment]
I get the desire not to help evil corporations or w/e but if it helps people I'm for it.  I doubt they would bother to link up anyways so its probably mute. 

But it would be nice to filter down the restaurants im searching for by ones with bathrooms I can use.

**Comment by Hkly** [comment]
I also think there is also high value in Refuge being made for and by the community. We all know yelp is just a for profit company. Refuge could provide more insight to the restroom availability/welcomness than yelp can/would. And there are definitely folks who don't use yelp, like me, that would use Refuge.

**Comment by daguar** [comment]
One approach that might be worth considering is simply asking them for the :+1: to pull the data they collect into RefugeRestrooms.

At the end of the day, they're doing this because (a) some folks there think it's the right thing to do, and (b) they interpret it as a good press opportunity.

If that request really doesn't require much of them beyond saying "yes it's okay to scrape via our API" and maybe give an unrestricted API key, then they get to say they're working with the existing community — and also if they say "no" it's pretty crappy optics for them...

I'm definitely not in a place to say whether this is the _right_ call for the team/community, but just adding it as a generative idea — it would potentially provide a real nice ongoing source of data to import and I feel like they'd have a hard time saying no.

(Also as an aside I worked a little bit with Yelp years ago helping doing entity-matching to get open data on health inspection score from cities merged in, and so would be happy to see if I can be helpful if that kind of merging was useful.)

Anyway, random brainstorming thought!

**Comment by daguar** [comment]
(Also I just tried to add a bathroom to a location on both the web and latest mobile versions of Yelp and it's not actually there yet, so also it's kinda vaporware until it's a live feature.)
