### ISSUE TITLE
[DEV] Vagrant File Sync not seeming to operate properly. 

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#299]
I'm having trouble with the Vagrant not syncing changes I make into the VM. 
Not sure what the issue is, am able to sync it by doing `vagrant reload` guessing the requirements changed for the syntax or something

**Comment by mi-wood** [comment]
@tkwidmer can you post your fix for this? I'm going to re-setup my dev environment and try to matte out and quirks in a bit, but I think you used `rsync-auto` right?

**Comment by dannypaz** [comment]
@mi-wood the only way I have been able to get vagrant to update repo is with `vagrant reload --provision`

**Comment by tkwidmer** [comment]
I think this is closed, we determined the only way to do it is to run the rsync-auto command

**Comment by DeeDeeG** [comment]
I've been doing `vagrant rsync-auto` and it has been working as expecting, keeping files in sync and such.

**Comment by DeeDeeG** [comment]
I know this is closed, but I discovered that going from 
config.vm.synced_folder ".", "/vagrant/", type: "**rsync**",
to
config.vm.synced_folder ".", "/vagrant/", type: "**virtualbox**", in the Vagrantfile eliminates the need to run `rsync --auto`.

**Comment by tkwidmer** [comment]
Oh, let's do that! @DeeDeeG we should get a PR open with that change. @mi-wood

**Comment by mi-wood** [comment]
@DeeDeeG @tkwidmer the reason it's using `rsync` is to use the `exclude` option that other providers don't offer. I can't remember the exact issue (was two years ago), but syncing `.bundle` can cause some issues`

**Comment by DeeDeeG** [comment]
I couldn't find .bundle in my repository, I think it's in the .gitignore?

**Comment by mi-wood** [comment]
Yes, but Vagrant isn't aware of `.gitignore` when it syncs files

**Comment by DeeDeeG** [comment]
I meant that, I figured if it's ignored by git, I'm not getting it when I clone from github.

(I note now from the git Docs that that isn't necessarily true: https://git-scm.com/docs/gitignore#_description)

Still, I didn't see it in my local folders anywhere. 

(Maybe this is only an issue if you are a general ruby developer? I see here that there can be a .bundle folder in the home directory, at `~/.bundle`. http://bundler.io/v1.14/man/bundle-install.1.html#SUDO-USAGE)

**Comment by mi-wood** [comment]
Yeah, `.bundle` is created during `bundle install`. You can see it's part of the `setup.sh` file. If you've run that, it will actually be in the repo in your Vagrant box and without the exclude would be synced back to your local directory

**Comment by DeeDeeG** [comment]
Okay, I'm poking around in my vagrant instance to double check this, and it looks alright to me:

We are syncing between the GitHub folder `refugerestrooms` on the real host, and `/vagrant` on the vagrant box. We should be safe from syncing the .bundle file, since it's not in either folder, or any of either folder's subfolders. 

For my double-checking: I did a `ls -la` and I didn't see it in `/vagrant`, which I am pretty sure is the only folder we sync back to the real machine (I do see it on the vagrant machine at `~/.bundle` where the bundler docs say it should be).

**Comment by mi-wood** [comment]
Hmm, looks like it's not actually from `bundle install` but holds config files. It's been awhile since I've looked at this stuff. Since it doesn't appear to be an issue right now, but file syncing is, we can move back to using the default vagrant sync functionality and get rid of the declaration altogether. Vagrant automatically syncs the repo root to `/vagrant` I believe
