### ISSUE TITLE
Update export.csv data

### ISSUE THREAD

**Issue by dannypaz** [RefugeRestrooms/refugerestrooms#303]
`db/export.csv` hasn't been updated in almost 3 years, so the data _may_ be stale. We should make sure these locations are correct/up to date.

**Comment by vernistage** [comment]
**Discrepancies:** 
- 12, Mission Creek Cafe is permanently closed per Yelp & Google.
- 14, Rainbow Grocery Co-op is listed as "Rainbow Grocery"
- 17, Cafe Roma is listed as "Caffe Roma"
- 18, Maxfield's House of Caffine is "Maxfield's House of Caffeine"
- 19, Cafe Espresso is permanently closed per Yelp & Google
- 21, Muddy Water's is "Muddy's Coffee House" and is now at 1304 Valencia St San Francisco, CA 94110
- 40,Philz Coffee there is no longer a Philz Coffee at 3901 18th St
- 38,Bang San Thai Restuarant is just "Bang San Thai"
- 66,New College is permanently closed
- 42,Sparky's Diner is permanently closed
- 50,Muddy Water's Coffee is Muddy Waters Coffee House
- 51,GLBT Historical Society is now at 989 Market St, San Francisco, CA 94103
- 53,LGBT Community Center is "The SF LGBT Center"
- 68,maggie mudd ice cream is permanently closed

I went ahead and updated the csv file and am making a pull request.

**Comment by manchicken** [comment]
Is this still open?

**Comment by DeeDeeG** [comment]
Hi @manchicken,

Thanks for your interest in contributing to our project, and I hope you are having a good Hacktoberfest so far!

This is still open, but it's a fairly low-stakes issue at this point. It turned out to be a bit of a non-issue, and fixing it proved problematic at the time as well.

(longer explanation: It turned out that these are only "dummy locations," used to populate our site during development. They are only there to make it possible to browse locations, and to otherwise test the app against them. and one of the locations was hard-coded into an automated test, which made it suddenly much more effort to update this and not break our tests.)

If you are able to update these so they better match the real world (with some extra considerations as follows) I would be okay with merging the changes:

- In my opinion, permanently closed locations probably should remain in the data set, so we don't run short on "dummy entries".
  - Or they could be replaced with new entries. I guess one could browse real entries in San Francisco at refugerestrooms.org and write a couple of those into the set of dummy entries... Not required! just a thought.
- If any updated entries cause our automated testing to break, we should probably just leave that entry unchanged.. -- Last time around, changing the entry for Mission Creek Cafe broke our automated testing, because there was a test that expected an entry with that exact name. However, the tests have been updated since then, so that might not be a problem anymore.

(We can tell you which changes, if any, have made the tests misbehave, it's usually not very tricky to tell.)

I hope that answers the question, and if there is any more info you need, let us know.

Best,

\- DeeDeeG

**Comment by manchicken** [comment]
This seems like something that you’d want to automate. Can you think of any way you’d want to automate this task? 

~ Michael D. Stemle, Jr.

**Comment by DeeDeeG** [comment]
Hi again Michael,

We do have an API to access (more-or-less real or current) database entries: https://refugerestrooms.org/api/docs/#!/restrooms

I'm not very familiar with how to use this, I don't personally do a lot of coding and backend stuff. But I think getting a few entries somewhere in San Francisco with the API would be a good way to populate this .csv with real, current data (to the extent that our production db is current).

Best, 
\- DeeDeeG

_P.S. Sorry for the delayed response, I somehow missed the notification that you had replied._

**Comment by DeeDeeG** [comment]
To clarify that this is not an active problem that we need to fix, I'm going to be closing this issue. Thanks everyone for your comments and input.

---

If we do update this (for sentimental reasons?) at some point, I recommend we do an API query against a location in San Francisco as described above to get the data. This is consistent with the current set of dummy entries being in San Francisco.

An example query to get this data: https://refugerestrooms.org/api/v1/restrooms/by_location.json?per_page=21&lat=37.7749&lng=-122.4194

We souls then filter out duplicate entries, or potentially ones that have bad ratings associated with them in production. I think 21 entries like we currently have is a good number of dummy entries.

This would just be for sentimental reasons, though, since the entries in `db/export.csv` are all placeholders, only used during development.  (They were exported from the production `db` a long time ago. But the copy was in the direction of "from production to development," and these entries are never copied the other way around: from the `export.csv` to our production database.)
