### ISSUE TITLE
Allign accessibilty filter icons

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#320]
Icons get aligned with the start of the distance text. This means that they aren't aligned between listing, which seems a little odd to me. Maybe we can align right instead.

**Comment by mi-wood** [comment]
For some reason, image uploads are broken for me right now. Will upload screenshot when I can

**Comment by mi-wood** [comment]
Might make more sense to just align the distance text instead too.

**Comment by kurtcarpenter** [comment]
Considered also displaying the filter icons horizontally instead of vertically? If/when more filter icons are present, three or more won't really fit as is.

Also, illustration of what mi-wood was mentioning:
<img width="879" alt="misaligned" src="https://user-images.githubusercontent.com/9683513/27107921-a66b15e6-5068-11e7-84e9-e676e85fee5b.PNG">
