### ISSUE TITLE
Make Contributing Guide More Generic and Accessible

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#321]
Link contributing guide from readme and/or github.io

**Comment by DeeDeeG** [comment]
I started a pull request https://github.com/RefugeRestrooms/refugerestrooms/issues/324 that does the easy part of this, but if it needs changes feel free to make them/let me know what to change. If this isn't what you had in mind and you want to start from scratch that's okay, too.

**Comment by DeeDeeG** [comment]
Still to do would be to add contributing.md to github.io, which I take to mean https://refugerestrooms.github.io

Not much going on there yet, and the page looks like it's about all of Refuge, including housing and so on. So it's hard to make a segue from the site being about all of Refuge, to "here is how to tinker on and test the website for Refuge Restrooms."

(When I put it that way, we could just put a blurb that says: "Help us test/develop RefugeRestrooms.org!")

I believe I could add the link if folks want it added. I would just hesitate, because CONTRIBUTING.md is a pretty deep dive for newcomers, and may not be what they should be seeing right off the bat.

I think CONTRIBUTING.md has been envisioned as a general guide for how to start contributing, but right now it's being focused on running the server in a vagrant box, and some other miscellaneous code/data quality tasks.

**Comment by mi-wood** [comment]
@DeeDeeG I think making the contributing doc more generally would be great. We could always move the current one to `setup.md` or something and link it from `contributing.md`

**Comment by mi-wood** [comment]
I think maybe we can link the wiki from the readme and close this? I didn't realize how much work was put into it already :) What'd you say @DeeDeeG @tkwidmer ?

**Comment by DeeDeeG** [comment]
+1 for linking to the Wiki from README, and also +1 for closing this as fixed, since I think the Wiki is currently trying to be not much short of comprehensive docs for working on the site.

Suggest linking to it right below `CONTRIBUTING.md`

```
## Contributing

Changes to the site can be tested locally before deploying to the web. To get set up to edit the site and test your changes, see [`CONTRIBUTING.md`](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/CONTRIBUTING.md).

For more information on how the technology powering Refuge Restrooms works, or how to get started from scratch, see the [Wiki](https://github.com/RefugeRestrooms/refugerestrooms/wiki).
```

**Comment by mi-wood** [comment]
@DeeDeeG how's this look? https://github.com/RefugeRestrooms/refugerestrooms/pull/436/files
