### ISSUE TITLE
HTML injection vulnerability.

### ISSUE THREAD

**Issue by iforgotband** [RefugeRestrooms/refugerestrooms#388]
Overview

cucumber is behavior Driven Development with elegance and joy.

Affected versions of the package are vulnerable to HTML Injection. The HTML formatter appends any scenario output to the HTML without escaping HTML tags in the messages. This way, any output from the steps gets injected into the report page. In the simple case, this won't display the message as expected. When combined with for example capybara and CI environments this opens up the possibility of an XSS attack from the user input on the environment being tested.

Remediation

There is no fix version for cucumber, yet.

**Comment by mi-wood** [comment]
Looks like someone put in a fix, but it didn't get merged https://github.com/cucumber/cucumber-ruby/pull/1056

**Comment by DeeDeeG** [comment]
We removed Cucumber from the project recently, in favor of just using Rspec for all tests.

Closing the issue since we're no longer potentially affected. (see [Gemfile.lock](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/Gemfile.lock) to confirm...)

Thanks for this report, @iforgotband.
