### ISSUE TITLE
Documentation Edit - Add Notes to "How do I translate Refuge Restrooms.org?"

### ISSUE THREAD

**Issue by hnarasaki** [RefugeRestrooms/refugerestrooms#553]
**Translating the Files Section:**

## Scope / difficulty

Easy/Minor documentation edit.

## Impact

A user might miss this and translate something that should not be translated.

## Proposal

On this page https://github.com/RefugeRestrooms/refugerestrooms/wiki/How-do-I-translate-Refuge-Restrooms.org%3F I would like to propose adding a note that if you see a value that is not in quotes, don't translate it.

Ex:

Do Translate: 
download-unisex-restroom-signs-hyperlink-label: **'I-download ang Mga Palatandaan ng Unisex na Silid'**
Don't Translate:
public-api-hyperlink-label: **Public API** 

**Putting Files in the New Folder Section**:

Would like to propose adding a note that you do not need to include "en.yml" file.

**Comment by DeeDeeG** [comment]
I think we can update that Wiki page, for sure. Thanks for the feedback. 

I want to address the comments you have given here.

> I would like to propose adding a note that if you see a value that is not in quotes, don't translate it.

> Do Translate:
> download-unisex-restroom-signs-hyperlink-label: **'I-download ang Mga Palatandaan ng Unisex na Silid'**
> Don't Translate:
> public-api-hyperlink-label: **Public API**

Actually if this phrase ("Public API") can be translated well into Filipino, that would be great! Of course, if it will make more sense without translation, that is fine also.

We should probably add quotes to the English translation file for this. (**Public API** --> **'Public API'**)

> Would like to propose adding a note that you do not need to include "en.yml" file.

Yes, that makes sense. We intended the "en.yml" to be deleted, but it keeps showing up again. I will go and make sure it is actually deleted in our main branch. Hopefully we won't need a note not to translate that file, since it won't exist anymore!

---

In general, I think that guide could be somewhat improved now that we've accepted several languages and are more familiar with how it usually goes. We can add what has been learned since the page was originally written.

(A side note: I'm surprised you aren't showing as an official "Contributor" to this repository on GitHub. Since we have accepted commits that you authored, you should be officially a "Contributor". And we have set up the wiki so that all Contributors are be able to edit the wiki. I'm not sure what happened there. If you wanted to edit that page directly (and if GitHub would let you??) you would be welcome to do so.)

**Comment by DeeDeeG** [comment]
Here is an update on one of these points. I agree that the `en.yml` file is confusing at the moment. I moved it out of the `en` folder and renamed it to `about_translations.yml`

(I decided to keep the file in some form, since it has some interesting technical information about how the translations work.) See: #554 

 If other members of the team agree with this, or if they don't comment on it for a while, I will merge that change into our main branch.

I will also edit the wiki page with better instructions for translating Refuge Restrooms, once I figure out what exactly to write.

Best regards,

\- DeeDeeG

**Comment by DeeDeeG** [comment]
Actually, it appears that I was wrong, and translations in `config/locales`don't need to be surrounded by quotes.

Here are some examples in the official documentation without quotes: 

from https://guides.rubyonrails.org/i18n.html#lazy-lookup :

```yml
en:
  books:
    create:
      success: Book created!
```

from https://guides.rubyonrails.org/i18n.html#using-safe-html-translations :

```yml
# config/locales/en.yml
en:
  welcome: <b>welcome!</b>
  hello_html: <b>hello!</b>
  title:
    html: <b>title!</b>
```

**Comment by DeeDeeG** [comment]
I removed the `en.yml` file from the `config/locales/en/` folder.

It is moved to the base folder of `config/locales/`, and renamed to `about_translations.yml`

**Comment by DeeDeeG** [comment]
Sure.

Might add something to the wiki later about quotation marks, if I can think of what would actually be helpful rather than unnecessary (or even accidentally confusing)... But for now we can close this. :+1:
