### ISSUE TITLE
Setup linting

### ISSUE THREAD

**Issue by tegandbiscuits** [RefugeRestrooms/refugerestrooms#643]
I noticed that it doesn't look like there's any linting inside the repo (correct me if I'm wrong), so I was wondering if I'd be able to setup `rubocop` (and also `rubocop-rspec` and `rubocop-rails`) then resolve any issues it finds?

I pulled this down and ran rubocop locally, and it looks like it's mostly just style changes and a few things to help maintenance.

**Comment by DeeDeeG** [comment]
Hi @tegandbiscuits, this was mentioned by another contributor just recently this week. So, it's starting to sound like something we should do.

Thanks for opening the issue.

Note to other maintainers: @tkwidmer @mi-wood if you have any thoughts or insights about this, objections, whatever, feel free to let me know. Otherwise I am going to look into just adding this myself.

**Comment by tegandbiscuits** [comment]
If it'd be helpful, I could make a pull request for it. I've already got it mostly done in a fork and could make a pull request with it tonight (or a draft PR now).

**Comment by DeeDeeG** [comment]
That would be fine.

I took a look at the fork you mentioned, and fair warning: I can say this is a bit beyond my ability to meaningfully review. I would be hoping for the tests to pass, but beyond that, the changes are a bit above my level of Ruby expertise (which as you might guess isn't very much!). I'll have to ask some of the other maintainers to take a look at this in order to review it properly. And they may not be able to stop and look at it right away.

If you're okay with that, then a PR would be quite welcome. Thanks a bunch for working on this.
