### ISSUE TITLE
Update number of pages when filter is apply

### ISSUE THREAD

**Issue by marioa98** [RefugeRestrooms/refugerestrooms#645]
Hi, I was checking your production page and I notice that when you apply any filter for restrooms, the number of pages still the same.

Replication of the issue:

- Find a location, e.g. https://www.refugerestrooms.org/restrooms?lat=37.7749295&long=-122.41941550000001&search=San+Francisco.
- Enable/disable some filters.

No filters enabled:
![image](https://user-images.githubusercontent.com/33180745/95690692-16057100-0bdf-11eb-992f-ac499f2c2280.png)

Enable filters with 0 matches:
![image](https://user-images.githubusercontent.com/33180745/95690713-3a614d80-0bdf-11eb-9202-e65ff7f20a21.png)

Possible related issues: #479 and #226.

I would be glad to take a look on that if you want it.

**Comment by DeeDeeG** [comment]
Hi @marioa98,

There is another person looking into fixing this, see https://github.com/RefugeRestrooms/refugerestrooms/pull/638. It's stalled on working out some new bugs. I'll ask that contributor if there are any updates. You can work on a solution of your own as well, if you like. We will only be able to accept one solution to this at this repo, but perhaps there is some chance for collaboration on a single working solution? Will see what happens when I post in that issue asking for an update.

Thanks for your interest in solving this issue. ❤️

**Comment by marioa98** [comment]
Ok, I see that there is a previous solution on progress and I don't have any problem co-working with someone else.

Hoping for answer, thanks to you to let me collaborate

**Comment by DeeDeeG** [comment]
@marioa98 hi again,

just letting you know this issue was in fact solved. Thanks again for the interest in this.

Have a great Hacktoberfest if you're participating in that. 🎃
